'use strict';
const menu = document.querySelector('.menu-toggle');
const nav = document.querySelector('nav');
menu.addEventListener('click', () => {const open = menu.getAttribute('aria-expanded') !== 'true';menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close navigation':'Open navigation');menu.textContent=open?'Close −':'Menu +';nav.classList.toggle('open',open);});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Open navigation');menu.textContent='Menu +';}));
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('open')){menu.click();menu.focus();}});
document.querySelector('#copy-email').addEventListener('click',async()=>{const status=document.querySelector('#copy-status');try{await navigator.clipboard.writeText('rithwiknuguri13@gmail.com');status.textContent='Email copied';}catch{status.textContent='Use the email link above to contact Sai.';}setTimeout(()=>status.textContent='',5000);});
const canvas=document.querySelector('#network'),ctx=canvas.getContext('2d');
const reduced=window.matchMedia('(prefers-reduced-motion: reduce)');let paused=reduced.matches,frame=0,width=0,height=0,angle=0,pointerX=0,pointerY=0;
const motion=document.querySelector('#motion');function syncMotion(){motion.textContent=paused?'▶':'Ⅱ';motion.setAttribute('aria-label',paused?'Play animation':'Pause animation');motion.setAttribute('aria-pressed',String(paused));}syncMotion();
const nodes=Array.from({length:340},(_,i)=>{const y=1-2*(i+.5)/340,r=Math.sqrt(1-y*y),phi=i*Math.PI*(3-Math.sqrt(5));return{x:Math.cos(phi)*r,y,z:Math.sin(phi)*r};});
function resize(){const rect=canvas.getBoundingClientRect();width=rect.width;height=rect.height;const dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=width*dpr;canvas.height=height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);draw();}
function draw(){ctx.clearRect(0,0,width,height);const radius=Math.min(width*.39,height*.39);const ca=Math.cos(angle+pointerX),sa=Math.sin(angle+pointerX);const tilt=.27+pointerY,ct=Math.cos(tilt),st=Math.sin(tilt);const ps=nodes.map(n=>{const x=n.x*ca+n.z*sa,z=-n.x*sa+n.z*ca,y=n.y*ct-z*st,z2=n.y*st+z*ct;const p=2.8/(2.8-z2*.35);return{x:width/2+x*radius*p,y:height/2+y*radius*p,z:z2};});
for(let i=0;i<ps.length;i++){const a=ps[i];for(let j=i+1;j<ps.length;j++){const n=nodes[i],m=nodes[j];if((n.x-m.x)**2+(n.y-m.y)**2+(n.z-m.z)**2<.062){const b=ps[j],opacity=.045+((a.z+b.z+2)/4)*.19;ctx.strokeStyle=`rgba(197,240,130,${opacity})`;ctx.lineWidth=.55;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();}}}
ps.sort((a,b)=>a.z-b.z).forEach((p,i)=>{const opacity=.2+(p.z+1)*.37;ctx.fillStyle=`rgba(210,255,155,${opacity})`;ctx.beginPath();ctx.arc(p.x,p.y,p.z>.6?1.8:1,0,Math.PI*2);ctx.fill();});
ctx.strokeStyle='rgba(167,190,140,.17)';ctx.lineWidth=.7;ctx.beginPath();ctx.ellipse(width/2,height/2,radius*1.16,radius*.25,-.45,0,Math.PI*2);ctx.stroke();}
function tick(){if(!paused&&!document.hidden){angle+=.002;draw();}frame=requestAnimationFrame(tick);}motion.addEventListener('click',()=>{paused=!paused;syncMotion();});reduced.addEventListener('change',e=>{paused=e.matches;syncMotion();draw();});canvas.addEventListener('pointermove',e=>{if(paused)return;const r=canvas.getBoundingClientRect();pointerX=((e.clientX-r.left)/r.width-.5)*.3;pointerY=((e.clientY-r.top)/r.height-.5)*.2;});canvas.addEventListener('pointerleave',()=>{pointerX=0;pointerY=0;});new ResizeObserver(resize).observe(canvas);resize();tick();
const portraitScene=document.querySelector('.portrait-scene');
const interactiveCards=document.querySelectorAll('.project-visual');
function applyDepthState(){document.body.classList.toggle('motion-paused',paused);if(paused){portraitScene.style.setProperty('--portrait-rx','0deg');portraitScene.style.setProperty('--portrait-ry','0deg');interactiveCards.forEach(card=>{card.style.setProperty('--card-rx','0deg');card.style.setProperty('--card-ry','0deg');});}}
motion.addEventListener('click',applyDepthState);reduced.addEventListener('change',applyDepthState);applyDepthState();
portraitScene.addEventListener('pointermove',event=>{if(paused||event.pointerType==='touch')return;const r=portraitScene.getBoundingClientRect();const x=(event.clientX-r.left)/r.width-.5,y=(event.clientY-r.top)/r.height-.5;portraitScene.style.setProperty('--portrait-rx',`${-y*14}deg`);portraitScene.style.setProperty('--portrait-ry',`${x*20}deg`);pointerX=x*.3;pointerY=y*.2;});portraitScene.addEventListener('pointerleave',()=>{portraitScene.style.setProperty('--portrait-rx','0deg');portraitScene.style.setProperty('--portrait-ry','0deg');pointerX=0;pointerY=0;});
interactiveCards.forEach(card=>{card.addEventListener('pointermove',event=>{if(paused||event.pointerType==='touch')return;const r=card.getBoundingClientRect();card.style.setProperty('--card-rx',`${-((event.clientY-r.top)/r.height-.5)*6}deg`);card.style.setProperty('--card-ry',`${((event.clientX-r.left)/r.width-.5)*8}deg`);});card.addEventListener('pointerleave',()=>{card.style.setProperty('--card-rx','0deg');card.style.setProperty('--card-ry','0deg');});});
